### ISSUE TITLE
Consider adding Pramda

### ISSUE THREAD

**Issue by kapolos** [xgrommx/awesome-functional-programming#3]
As per the title :)

Pramda: Practical Functional Programming in PHP

https://github.com/kapolos/pramda

**Comment by xgrommx** [comment]
Sure! Welcome to PR =)

**Comment by xgrommx** [comment]
Probably I did it and this issue should be closed.

**Comment by kapolos** [comment]
Sorry for being late, I was planning to do this during the weekend. Thanks for adding it :+1:
